version: "3.8" 
services:
  modifiedshop-server:
    image: modifiedshop-server:latest
    build:
      context: .
      dockerfile: modifiedshop-server.Dockerfile
    command: -S 0.0.0.0:4000 -t .
    ports:
      - "4000:4000"
    volumes:
      - ".:/usr/src/modifiedshop"
    working_dir: /usr/src/modifiedshop
    networks:
      - "modifiedshop-net"
  modifiedshop-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./init-sql/:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    networks:
      - "modifiedshop-net"
    depends_on:
      - modifiedshop-server

networks:
  modifiedshop-net:
      
